language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run python -m pytest

after_success:
  - pipenv run python -m coveralls
