language: python
python:
  - "2.7"
  - "3.3"
install: "python setup.py install"
install: "pip install coveralls"
script:
  - nosetests  --with-coverage --cover-package=Wappalyzer
after_success:
  - coveralls